[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "PyBloomer"
dynamic = ["version"]
requires-python = ">= 3.10"
dependencies = [
  "numpy>=1.19.5",
]
authors = [
  {name = "Andrew DalPino", email = "support@andrewdalpino.com"},
]
description = "PyBloomer is an implementation of the OkBloomer algorithm, an autoscaling Bloom filter with ultra-low memory footprint for Python."
readme = "README.md"
license = {text = "MIT"}

[project.urls]
Homepage = "https://github.com/andrewdalpino/PyBloomer"
Documentation = "https://github.com/andrewdalpino/PyBloomer/README.md"
Source = "https://github.com/andrewdalpino/PyBloomer"
